name: "Query developer statistics"
description: "Query developer statistics from GitHub, and upload compressed JSON bundle as an artifact."

inputs:
  repos:
    description: "The GitHub repositories to query for devstats; a
  string of format: '[username/reponame1, username/reponame2]'"
    required: true
  token:
    description: "A Github Personal Access Token with `public_repo` permission"
    required: true
  artifact-name:
    description: "Name given to the uploaded artifact (zip file of all devstats bundles)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install devstats
      env:
        DEVSTATS_SHA: 5978e8d87d76851944c80d52c7fc646ca804ac18
      shell: bash
      run: |
        pip install git+https://github.com/scientific-python/devstats.git@${DEVSTATS_SHA}
    - name: Download data
      env:
        GRAPH_API_KEY: ${{ inputs.token }}
        REPOS: ${{ inputs.repos }}
      shell: bash
      run: |
        echo $REPOS
        for REPO in $REPOS; do
          OWNER_REPO=($(echo $REPO | tr "/" " "))
          devstats query ${OWNER_REPO[0]} ${OWNER_REPO[1]} >> $GITHUB_STEP_SUMMARY
        fi
    - name: Bundle data
      env:
        REPOS: ${{ fromJSON(inputs.repos) }}
      shell: bash
      run: |
        for REPO in $REPOS; do
          OWNER_REPO=($(echo $REPO | tr "/" " "))
          FILENAME="$(date +"%Y-%m-%d")-devstats-${OWNER_REPO[1]}.xz"
          cd devstats-data
          echo "\nCreating archive $FILE..." >> $GITHUB_STEP_SUMMARY
          tar cfJ $FILENAME *_issues.json *_PRs.json
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: "devstats-data/*.xz"
