name: "Query developer statistics"
description: "Query developer statistics from GitHub, and upload compressed JSON bundle as an artifact."

inputs:
  repos:
    description: >-
      The GitHub repositories to query for devstats; a string
      containing a YAML list, e.g. '[username/reponame1, username/reponame2]'
    required: true
  token:
    description: "A Github Personal Access Token with `public_repo` permission"
    required: true
  artifact-name:
    description: "Name given to the uploaded artifact (zip file of all devstats bundles)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install devstats
      env:
        DEVSTATS_SHA: 5978e8d87d76851944c80d52c7fc646ca804ac18
      shell: bash
      run: |
        pip install git+https://github.com/scientific-python/devstats.git@${DEVSTATS_SHA}
    - name: Download data
      env:
        REPOS: ${{ inputs.repos }}
        GRAPH_API_KEY: ${{ inputs.token }}
      shell: bash
      run: |
        REPOS_JSON=$(python -c "import yaml, json, sys; print(json.dumps(yaml.safe_load(sys.argv[1].replace(r'\n', ''))))" "$REPOS")
        REPOS_JSON_SPLIT=$(echo $REPOS | jq -c '.[] | [split("/")] | {org: .[1], repo: .[2]}')

        for ORG_REPO in $REPOS_JSON_SPLIT; do
          ORG=$(echo $ORG_REPO | jq -r ".org")
          REPO=$(echo $ORG_REPO | jq -r ".repo")
          FILENAME="$(date +"%Y-%m-%d")-devstats-$ORG.xz"

          echo "Querying $ORG/$REPO..." >> $GITHUB_STEP_SUMMARY
          devstats query $ORG $REPO >> $GITHUB_STEP_SUMMARY

          echo "\nCreating archive $FILENAME..." >> $GITHUB_STEP_SUMMARY
          (cd devstats-data; tar cfJ $FILENAME *_issues.json *_PRs.json)
        done
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: "devstats-data/*.xz"
